version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx-ubuntu-compose:latest
    ports:
      - "8080:80"       
    restart: unless-stopped
    volumes:
      - ./:/workspace:ro   
