version: "3.9"

services:
  app1:
    build: ./app1
    container_name: flask_app1
    env_file:
      - ./config.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  app2:
    build: ./app2
    container_name: flask_app2
    env_file:
      - ./config.env
    ports:
      - "5001:5001"
    depends_on:
      - app1
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: flask_nginx
    env_file:
      - ./config.env
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - app1
      - app2
    restart: unless-stopped

networks:
  default:
    name: flask_network
