version: "3.9"

networks:
  pankhuri:
    driver: bridge

services:
  api2:
    build: ./api2
    container_name: api2
    ports:
      - "5002:5002"
    networks:
      - pankhuri

  api1:
    build: ./api1
    container_name: api1
    ports:
      - "5001:5001"
    depends_on:
      - api2
    networks:
      - pankhuri
